FROM bitnami/spark:3.4.1

USER root
RUN apt-get update && apt-get install -y python3-pip && pip3 install numpy
RUN mkdir -p /tmp/spark-events && chmod 777 /tmp/spark-events

COPY spark-defaults.conf /opt/bitnami/spark/conf/
